console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F8F32B'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    leading_diamond = ' '
    trailing_diamond = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  style = 'plain'
  template = "{{ .Shell }}\n❯ "
