console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  dark_blue = '#0b006b'
  sky_blue = '#00b7ff'
  gray = '#303030'
  green = '#5dd003'
  orange = '#ff810a'
  red = '#bd1e1e'
  white = '#E0DEF4'
  yellow = '#F8F32B'

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "text"
    style = "diamond"
    leading_diamond = "\uE0B2"
    trailing_diamond = ""
    foreground = "p:orange"
    background = "p:gray"  # color por defecto (no root)
    background_templates = [
      "{{ if .Root }}p:red{{ end }}"
    ]
    template = " {{ .UserName }} "

  [[blocks.segments]]
    type = "path"
    style = "diamond"
    leading_diamond = "\uE0B2"
    trailing_diamond = ""
    foreground = "p:sky_blue"
    background = "p:gray"

    [blocks.segments.properties]
      style = "full"
 
  [[blocks.segments]]
    type = "git"
    style = "diamond"
    trailing_diamond = ""
    leading_diamond = "\uE0B2"
    foreground = "p:green"
    background = "p:gray"

    [blocks.segments.properties]
      branch_icon = " "

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{ if gt .Code 0}}p:red{{ end }}",
      "{{ if eq .Code 0}}p:green{{ end }}",
    ]
    background = "transparent"
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{ if gt .Code 0}}p:red{{ end }}",
    "{{ if eq .Code 0}}p:green{{ end }}",
  ]
  background = "transparent"
  template = '❯ '
